default: &default
  adapter: mysql2
  encoding: utf8
  username: root
  password:
development:
  <<: *default
  database: demo_vuejs_rails_development
production:
  <<: *default
  database: demo_vuejs_rails_production
  username: <%= ENV["DB_USER"] %>
  password: <%= ENV["DB_PASSWORD"] %>
  host: <%= ENV["DB_HOST"] %>
