default: &default
  adapter: mysql2
  encoding: utf8
  user: root
  password:
development:
  <<: *default
  database: demo_vuejs_rails_development
production:
  <<: *default
  database: demo_vuejs_rails_production
